// <auto-generated />
using CityInfo.API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CityInfo.API.Migrations
{
    [DbContext(typeof(CityInfoContext))]
    [Migration("20231128184013_CityInfoDBFixPointOfInterestCollection")]
    partial class CityInfoDBFixPointOfInterestCollection
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("CityInfo.API.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The one with the Crazy Liquor laws and Beautiful Mountains.",
                            Name = "Salt Lake City"
                        },
                        new
                        {
                            Id = 2,
                            Description = "The one that I'm moving to!!!",
                            Name = "Portland"
                        },
                        new
                        {
                            Id = 3,
                            Description = "The one with Disneyland!",
                            Name = "Anaheim"
                        });
                });

            modelBuilder.Entity("CityInfo.API.Entities.PointOfInterest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("PointsOfInterest");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Description = "Home of the Utah Jazz!",
                            Name = "Delta Center"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 2,
                            Description = "Has a lot of animals.",
                            Name = "Portland Zoo"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 2,
                            Description = "All the bridges over the rivers",
                            Name = "Bridges"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 3,
                            Description = "The happiest (and most expensive) place on earth.",
                            Name = "Disneyland"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 3,
                            Description = "Right next to Disneyland, has a lot of other rides",
                            Name = "California Adventure"
                        });
                });

            modelBuilder.Entity("CityInfo.API.Entities.PointOfInterest", b =>
                {
                    b.HasOne("CityInfo.API.Entities.City", "City")
                        .WithMany("PointsOfInterest")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("CityInfo.API.Entities.City", b =>
                {
                    b.Navigation("PointsOfInterest");
                });
#pragma warning restore 612, 618
        }
    }
}
